os: linux
dist: xenial
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6

branches:
  only:
  - master

script: make && ./testdigraph
